# Generated by Django 3.2.23 on 2024-02-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_threshold', models.PositiveIntegerField(default=20)),
                ('min_order_quantity', models.PositiveIntegerField(default=100)),
                ('supplier_name', models.CharField(blank=True, max_length=100)),
                ('supplier_email', models.EmailField(blank=True, max_length=254)),
                ('last_reorder_date', models.DateField(blank=True, null=True)),
                ('is_expecting_delivery', models.BooleanField(default=False)),
                ('cost_per_product', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('total_units_sold', models.PositiveIntegerField(default=0)),
                ('total_lost_or_damaged', models.PositiveIntegerField(default=0)),
                ('total_revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
