# Generated by Django 3.2.23 on 2024-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_set_default_supplier_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='ordered_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
