# Generated by Django 3.2.23 on 2024-02-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_rating_product_overall_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.reviews'),
        ),
    ]
