# Generated by Django 3.2.23 on 2024-02-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
